on: 
  push:
  workflow_dispatch:


jobs:
  build-il2cpp-windows:
    runs-on: windows-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      
      - shell: cmd
        name: Add editor folder
        run: mkdir \test-project\Assets\Editor

      - name: Add Build Scripts
        run: Copy-Item -Path "UnityBuilderAction" -Destination "test-project/Assets/Editor/UnityBuilderAction/" -Recurse
      
      - name: Make output folder
        run: mkdir output
      
      - name: Install Unity Hub
        run: choco install unity-hub --no-progress -y
        
      - name: Install Unity
        shell: cmd
        run: |
              "C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless install --version 2021.1.20f1 --changeset be552157821d --module windows-il2cpp & exit 0
        
      - name: Activate Unity
        env: 
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_USER: ${{ secrets.UNITY_USER }}
          UNITY_PASS: ${{ secrets.UNITY_PASS }}
        run: |
              & "C:\Program Files\Unity\Hub\Editor\2021.1.20f1\Editor\Unity.exe" -batchmode -quit -nographics `
                                                                                -username $Env:UNITY_USER `
                                                                                -password $Env:UNITY_PASS `
                                                                                -serial $Env:UNITY_SERIAL `
                                                                                -logfile | Out-Host
      
      - name: Build Project
        run: |
              & "C:\Program Files\Unity\Hub\Editor\2021.1.20f1\Editor\Unity.exe" -quit -batchmode -nographics `
                                                                          -projectPath test-project `
                                                                          -executeMethod UnityBuilderAction.Builder.BuildProject `
                                                                          -buildTarget StandaloneWindows64 `
                                                                          -customBuildTarget StandaloneWindows64 `
                                                                          -customBuildPath ../output/output.exe `
                                                                          -buildVersion v1.0.0 `
                                                                          -androidVersionCode 1 `
                                                                          -logfile | Out-Host
        
      - name: Return License
        env:
          UNITY_USER: ${{ secrets.UNITY_USER }}
          UNITY_PASS: ${{ secrets.UNITY_PASS }}
        run: |
              & "C:\Program Files\Unity\Hub\Editor\2021.1.20f1\Editor\Unity.exe" -batchmode -quit -nographics `
                                                                                        -username $Env:UNITY_USER `
                                                                                        -password $Env:UNITY_PASS `
                                                                                        -returnlicense `
                                                                                        -logfile | Out-Host

      - uses: actions/upload-artifact@v2
        with:
          name: Upload Output Build
          path: output/
