on: 
  push:
  workflow_dispatch:
    inputs:
      modules:
        description: 'Supported Modules'
        required: true
        default: 'windows-il2cpp, base'
      


jobs:
  build-il2cpp-windows:
    if: ${{contains(inputs.modules, matrix.targetPlatform)}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - base
          - windows-il2cpp
          - universal-windows-platform
          - uwp-il2cpp
          - appletv
    
    steps:
      - name: Echo
        run: echo ${{inputs.modules}}
        
