on: push

jobs:
  install-unity-hub:
    runs-on: windows-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: list files
        run: dir
        
      - name: Install Unity Hub
        run: choco install unity-hub --no-progress -y
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
              python get_activation_file.py

      - uses: actions/upload-artifact@v2
        with:
          name: Upload Activation File
          path: Unity_v2020.3.24f1.alf
