on: 
  workflow_dispatch:
      inputs:
        jobId:
          description: 'Job ID'
          required: true
          default: '0'
        editorVersion:
          description: 'Unity Editor Version'
          required: true
          default: '2020.3.24f1'
        changeSet:
          description: 'Unity Editor Changeset'
          required: true
          default: '79c78de19888'
        repoVersionFull:
          description: 'Docker Repo Version Full'
          required: true
          default: '0.15'
        repoVersionMinor:
          description: 'Docker Repo Version Minor'
          required: true
          default: '15'
        repoVersionMajor:
          description: 'Docker Repo Version Major'
          required: true
          default: '0'

jobs:
  test-actions:
    runs-on: windows-latest
    
    steps:
      - name: Wrangle Inputs
        id: workflow_variables
        run: |
              echo "Event ${{ github.event }}" && echo "${{ github.event.inputs }}"
