on: push

jobs:
  test-commands:
    runs-on: windows-latest
    
    steps:
      - name: List Drive Sizes
        run: get-PSDrive
      
      - name: Dir Sizes
        run:  Get-ChildItem -Path "C:/"
      
      - name: Dir Sizes 2
        run: dir "c:\"
