on: push

jobs:
  install-unity-hub:
    runs-on: windows-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: Install Unity Hub
        run: choco install unity-hub --no-progress -y
       
      - name: Install Version
        run: |
          "C:/Program Files/Unity Hub/Unity Hub.exe -- --headless install --version 2020.3.24f1 --changeset 79c78de19888"
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
              python run.py
